Add docker build and run

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -13,3 +13,26 @@ jobs:
     steps:
     - name: Checkout code
       uses: actions/checkout@v4
+
+    - name: setup Docker Buildx
+      uses: docker/setup-buildx-action@v3
+
+    - name: Build Docker image
+      run: |
+        docker build -t events-api:latest .
+
+    - name: Run container
+      run: |
+        docker run -d -p 5000:5000 --name events-api-test events-api:latest
+        for i in {1..20}; do
+          if curl -fsS http://localhost:5000/api/health; then
+            echo "Health check OK"
+            exit 0
+          fi
+          echo "Waiting for API...($i)"
+          sleep 1
+        done
+        
+        echo "Health check failed"
+        docker logs events-api-test || true
+        exit 1
